spring:
  datasource:
    url: ${spring.datasource.url}                                                       #jdbc:mysql://localhost:3306/bankapp
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: false
    open-in-view: false
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml